

from datetime import timedelta

from django.utils import timezone
from django.db.models import Count

from apps.user.models import User, Follow
from . import constants
import statistics
from apps.posts.models import Comment, Post, Like
from .models import BotEvent, BlocklistTerm, SpamPhrase
import re
from .text_similarity import TextSimilarityService
from .graph_analysis import FollowGraphService
from .spam_classifier import SpamClassifierService
from collections import Counter

#logs the event into the event table
def _log_detection(user, event_type, detail):
    BotEvent.objects.get_or_create(
        user=user,
        event_type=event_type,
        detail=detail,
    )

#this return a name without numbers or symbols
def _username_stem(username: str) -> str:
    stem = re.sub(r'\d+$', '', username)
    stem = re.sub(r'[._-]+$', '', stem)
    return stem

#algorith that calculates the levensthein distance
def _levenshtein_distance(s1: str, s2: str) -> int:

    m = len(s1)
    n = len(s2)

    dp = [[0] * (n + 1) for _ in range(m + 1)]

    # Base cases: transforming to/from empty string.
    for j in range(n + 1):
        dp[0][j] = j   # j insertions needed
    for i in range(m + 1):
        dp[i][0] = i   # i deletions needed

    for i in range(1, m + 1):
        for j in range(1, n + 1):
            if s1[i - 1] == s2[j - 1]:
                dp[i][j] = dp[i - 1][j - 1]
            else:
                dp[i][j] = 1 + min(
                    dp[i - 1][j],       # delete from s1
                    dp[i][j - 1],       # insert into s1
                    dp[i - 1][j - 1],   # substitute
                )

    return dp[m][n]


class BotDetectionEngine:

    @staticmethod
    def check_username_pattern(user):
        """
        # method is used to check if either the digit ratio in a username is bigger than a threshold
        and if there a re a certain number of digits at the end of a username
        """
        username = user.username
        if not username:
            return 0, None

        digit_count = sum(c.isdigit() for c in username)
        digit_ratio = digit_count / len(username)

        trailing = 0
        for c in reversed(username):
            if c.isdigit():
                trailing += 1
            else:
                break

        if (
            digit_ratio >= constants.USERNAME_DIGIT_RATIO # 0.4
            or trailing >= constants.USERNAME_TRAILING_DIGITS #4
        ):
            reason = "many digits into the username, looks autogenerated(check username pattern)"
            _log_detection(user, BotEvent.EventType.SUSPICIOUS_USERNAME, reason)
            return constants.POINTS['username_pattern'], reason
        return 0, None

    @staticmethod
    def check_username_blocklist(user):
        """
        checks if the username is present in a database table of blocklisted usernames
        :param user:
        :return:
        """
        lowered = user.username.lower()
        active_terms = BlocklistTerm.objects.filter(is_active=True).values_list(
            'term', flat=True
        )

        for term in active_terms:
            if term.lower() in lowered:

                reason = f"Username contains blocklisted term '{term} (blocklist test)'"
                _log_detection(user, BotEvent.EventType.SUSPICIOUS_USERNAME, reason)
                return constants.POINTS['username_blocklist'], reason
        return 0, None


    @staticmethod
    def check_shared_ip(user):

        user_ips = (
            BotEvent.objects
            .filter(user=user)
            .exclude(ip_address__isnull=True)
            .values_list('ip_address', flat=True)
            .distinct()
        )       #values of the ips a user has been seen on

        for ip in user_ips:
            distinct_users = (
                BotEvent.objects
                .filter(ip_address=ip)
                .values('user')
                .distinct()
                .count()
            )
            if distinct_users >= constants.SHARED_IP_THRESHOLD: # constant is 3
                reason = f"IP {ip} shared by {distinct_users} accounts( ip test)"
                return constants.POINTS['shared_ip'], reason
        return 0, None

    @staticmethod
    def check_throttle_events(user):  # event logger logs thorrtle s inside a table and this method searches for them

        count = BotEvent.objects.filter(
            user=user,
            event_type=BotEvent.EventType.THROTTLED,
        ).count()

        if count == 0:
            return 0, None

        points = min(  # this prevents a bigger than 30 score, so if i thortlle 20 times it will be flagged but the score will be max 30
            count * constants.POINTS['throttle_event'],
            constants.THROTTLE_EVENT_CAP
        )
        return points, f"Hit rate limits {count} times(throotle test)"

    @staticmethod
    def check_failed_logins(user):      # this one also cheks for failed logins in the table
        count = BotEvent.objects.filter(
            event_type=BotEvent.EventType.FAILED_LOGIN,
            detail__icontains=f"attempted username: {user.username}",
        ).count()

        if count == 0:
            return 0, None

        points = min(
            count * constants.POINTS['failed_login'],
            constants.FAILED_LOGIN_CAP,         #same here for the login, a maxx of 20 points can be added to someone if it fails logins
        )
        return points, f"{count} failed login attempts"

    @staticmethod
    def check_repeated_comments(user):
        """
                #cet all of the coments and filter them by user,then get only the content of the specific list
                then annotate grooups them by content, if its equal, and it counts how many instances of that comment are there
                then it filters the one that have occurances greater than the threshold
        """
        repeated = (
            Comment.objects
            .filter(author=user)
            .values('content')
            .annotate(n=Count('id'))
            .filter(n__gte=constants.REPEATED_COMMENT_THRESHOLD)
        )

        if repeated.exists():
            worst = max(row['n'] for row in repeated)
            reason = f"Posted the same comment {worst} times" # keeps only the worst one

            BotEvent.objects.get_or_create(
                user=user,
                event_type=BotEvent.EventType.REPEATED_COMMENT,
                detail=reason,
            )

            return constants.POINTS['repeated_comment'], reason
        return 0, None

    @staticmethod
    def check_spam_phrases(user):   #the ones on the database
        active_phrases = list(
            SpamPhrase.objects.filter(is_active=True).values_list('phrase', flat=True) #flat true skips the touple
        )

        if not active_phrases:
            return 0, None

        # Check comments.
        comments = Comment.objects.filter(author=user).values_list('content', flat=True)
        for content in comments:
            lowered = content.lower()
            for phrase in active_phrases:
                if phrase.lower() in lowered:
                    reason = f"Comment contains spam phrase '{phrase}'"
                    BotEvent.objects.get_or_create(
                        user=user,
                        event_type=BotEvent.EventType.SPAM_CONTENT,
                        detail=reason,
                    )
                    return constants.POINTS['spam_phrase'], reason

        # Check bio.
        try:
            bio = user.profile.bio
            if bio:
                lowered_bio = bio.lower()
                for phrase in active_phrases:
                    if phrase.lower() in lowered_bio:
                        reason = f"Bio contains spam phrase '{phrase}'"
                        BotEvent.objects.get_or_create(
                            user=user,
                            event_type=BotEvent.EventType.SPAM_CONTENT,
                            detail=reason,
                        )
                        return constants.POINTS['spam_phrase'], reason
        except Exception:
            pass

        return 0, None

    @staticmethod
    def check_follow_velocity(user):
        """Following a lot of accounts in a short window is bot-like."""
        window_start = timezone.now() - timedelta(
            minutes=constants.FOLLOW_VELOCITY_WINDOW_MINUTES
        )
        recent_follows = Follow.objects.filter(
            follower=user,
            created_at__gte=window_start,
        ).count()

        if recent_follows >= constants.FOLLOW_VELOCITY_THRESHOLD:
            reason = (
                f"Followed {recent_follows} accounts in the last "
                f"{constants.FOLLOW_VELOCITY_WINDOW_MINUTES} minutes"
            )
            BotEvent.objects.get_or_create(
                user=user,
                event_type=BotEvent.EventType.RAPID_FOLLOW,
                detail=reason,
            )
            return constants.POINTS['follow_velocity'], reason
        return 0, None

    @staticmethod
    def check_profile_completeness(user):  # check if the user has a bio a profile and a profile picture

        try:
            profile = user.profile
        except Exception:
            reason = "No profile"
            _log_detection(user, BotEvent.EventType.INCOMPLETE_PROFILE, reason)
            return constants.POINTS['incomplete_profile'], reason

        has_pic = bool(profile.profile_pic)
        has_bio = bool(profile.bio and profile.bio.strip())

        if not has_pic and not has_bio:
            reason = "No picture and no bio"
            _log_detection(user, BotEvent.EventType.INCOMPLETE_PROFILE, reason)
            return constants.POINTS['incomplete_profile'], reason
        return 0, None

    @staticmethod
    def check_activity_burst(user):  # c
        window_start = timezone.now() - timedelta(
            minutes=constants.ACTIVITY_BURST_WINDOW_MINUTES
        )

        posts = Post.objects.filter(
            author=user, created_at__gte=window_start
        ).count()
        comments = Comment.objects.filter(
            author=user, created_at__gte=window_start
        ).count()
        likes = Like.objects.filter(
            author=user, created_at__gte=window_start
        ).count()
        follows = Follow.objects.filter(
            follower=user, created_at__gte=window_start
        ).count()

        total_actions = posts + comments + likes + follows

        if total_actions >= constants.ACTIVITY_BURST_THRESHOLD:
            reason = (
                f"{total_actions} actions in "
                f"{constants.ACTIVITY_BURST_WINDOW_MINUTES} minutes "
                f"({posts} posts, {comments} comments, {likes} likes, {follows} follows)"
            )
            _log_detection(user, BotEvent.EventType.ACTIVITY_BURST, reason)
            return constants.POINTS['activity_burst'], reason
        return 0, None


    @staticmethod
    def check_regular_rhythm(user):
        window_start = timezone.now() - timedelta(hours=constants.RHYTHM_WINDOW_HOURS)

        timestamps = []
        timestamps += list(
            Post.objects.filter(author=user, created_at__gte=window_start)
            .values_list('created_at', flat=True)
        )
        timestamps += list(
            Comment.objects.filter(author=user, created_at__gte=window_start)
            .values_list('created_at', flat=True)
        )
        timestamps += list(
            Like.objects.filter(author=user, created_at__gte=window_start)
            .values_list('created_at', flat=True)
        )
        timestamps += list(
            Follow.objects.filter(follower=user, created_at__gte=window_start)
            .values_list('created_at', flat=True)
        )


        if len(timestamps) < constants.RHYTHM_MIN_ACTIONS:
            return 0, None


        timestamps.sort()

        gaps = [
            (timestamps[i] - timestamps[i - 1]).total_seconds()
            for i in range(1, len(timestamps))
        ]

        avg_gap = statistics.mean(gaps)
        gap_stddev = statistics.stdev(gaps)

        if (
                gap_stddev < constants.RHYTHM_STDDEV_THRESHOLD
                and avg_gap <= constants.RHYTHM_MAX_AVG_GAP_SECONDS
        ):
            reason = (
                f"Machine-like timing: {len(timestamps)} actions evenly spaced "
                f"~{avg_gap:.0f}s apart (variation {gap_stddev:.1f}s)"
            )
            _log_detection(user, BotEvent.EventType.REGULAR_RHYTHM, reason)
            return constants.POINTS['regular_rhythm'], reason
        return 0, None

    @staticmethod
    def check_username_cluster(user):
        stem = _username_stem(user.username)
        if stem == user.username or not stem:
            return 0, None

        candidates = User.objects.filter(
            username__startswith=stem
        ).values_list('username', flat=True)

        cluster_size = sum(
            1 for name in candidates
            if _username_stem(name) == stem
        )

        if cluster_size >= constants.USERNAME_CLUSTER_THRESHOLD:
            reason = (
                f"Username part of a cluster of {cluster_size} "
                f"similar names ('{stem}...')"
            )
            _log_detection(user, BotEvent.EventType.USERNAME_CLUSTER, reason)
            return constants.POINTS['username_cluster'], reason
        return 0, None

    @staticmethod
    def check_fuzzy_username_cluster(user):
        username = user.username.lower()

        if len(username) < constants.CLUSTER_MIN_STEM_LENGTH:
            return 0, None

        all_usernames = (
            User.objects
            .exclude(pk=user.pk)
            .values_list('username', flat=True)
        )

        similar_count = 0
        for other in all_usernames:
            other_lower = other.lower()
            if len(other_lower) < constants.CLUSTER_MIN_STEM_LENGTH: #dont compare to short ones
                continue
            distance = _levenshtein_distance(username, other_lower)
            if distance <= constants.CLUSTER_FUZZY_DISTANCE:
                similar_count += 1

        if similar_count >= constants.USERNAME_CLUSTER_THRESHOLD:
            reason = (
                f"Username is edit-distance-close to {similar_count} "
                f"other accounts (possible bot farm)"
            )
            _log_detection(user, BotEvent.EventType.USERNAME_CLUSTER, reason)
            return constants.POINTS['fuzzy_cluster'], reason
        return 0, None

    @staticmethod
    def check_near_duplicate_comments(user):
        comments = list(
            Comment.objects.filter(author=user).values_list('content', flat=True)
        )

        if len(comments) < constants.NEAR_DUPLICATE_MIN_COMMENTS:
            return 0, None

        similar_pairs = TextSimilarityService.count_similar_pairs(
            comments, constants.NEAR_DUPLICATE_SIMILARITY_THRESHOLD
        )

        if similar_pairs >= constants.NEAR_DUPLICATE_PAIR_THRESHOLD:
            reason = (
                f"{similar_pairs} pairs of near-duplicate comments detected "
                f"(reworded spam pattern)"
            )
            BotEvent.objects.get_or_create(
                user=user,
                event_type=BotEvent.EventType.REPEATED_COMMENT,
                detail=reason,
            )
            return constants.POINTS['near_duplicate_comments'], reason

        return 0, None

    @staticmethod
    def check_duplicate_posts(user):
        posts = list(
            Post.objects.filter(author=user).values_list('title', 'content')
        )

        if len(posts) < constants.POST_SIMILARITY_MIN_POSTS:
            return 0, None

        # Combine title + content into one blob per post.
        blobs = [f"{title} {content}" for title, content in posts]

        similar_pairs = TextSimilarityService.count_similar_pairs(
            blobs, constants.POST_SIMILARITY_THRESHOLD
        )

        if similar_pairs >= constants.POST_SIMILAR_PAIR_THRESHOLD:
            reason = (
                f"{similar_pairs} pairs of near-duplicate posts detected "
                f"(reworded spam posts)"
            )
            _log_detection(user, BotEvent.EventType.DUPLICATE_POSTS, reason)
            return constants.POINTS['duplicate_posts'], reason

        return 0, None

    @staticmethod
    def check_duplicate_image(user):
        # Only posts that actually have an image.
        image_names = list(
            Post.objects
            .filter(author=user)
            .exclude(image='')
            .exclude(image__isnull=True)
            .values_list('image', flat=True)
        )

        if not image_names:
            return 0, None


        filenames = [name.split('/')[-1] for name in image_names]
        counts = Counter(filenames)

        most_common_name, most_common_count = counts.most_common(1)[0]

        if most_common_count >= constants.DUPLICATE_IMAGE_THRESHOLD:
            reason = (
                f"Reused the same image '{most_common_name}' "
                f"across {most_common_count} posts"
            )
            _log_detection(user, BotEvent.EventType.DUPLICATE_IMAGE, reason)
            return constants.POINTS['duplicate_image'], reason

        return 0, None

    @staticmethod
    def check_duplicate_post_burst(user):
        """
        detects posts with similar title and bio in a short burst
        """
        window_start = timezone.now() - timedelta(
            minutes=constants.POST_BURST_WINDOW_MINUTES
        )

        recent_posts = list(
            Post.objects
            .filter(author=user, created_at__gte=window_start)
            .values_list('title', 'content')
        )

        if len(recent_posts) < constants.POST_BURST_MIN_POSTS:
            return 0, None

        blobs = [f"{title} {content}" for title, content in recent_posts]

        if TextSimilarityService.has_similar_cluster(
                blobs, constants.POST_BURST_SIMILARITY_THRESHOLD
        ):
            reason = (
                f"{len(recent_posts)} posts in "
                f"{constants.POST_BURST_WINDOW_MINUTES} minutes with "
                f"near-duplicate content"
            )
            _log_detection(user, BotEvent.EventType.DUPLICATE_POST_BURST, reason)
            return constants.POINTS['duplicate_post_burst'], reason

        return 0, None

    @staticmethod
    def check_bot_network(user):
        cluster = FollowGraphService.get_user_cluster(
            user.id,
            constants.BOT_NETWORK_MIN_CLUSTER_SIZE,
            constants.BOT_NETWORK_MIN_DENSITY,
        )

        if cluster:
            reason = (
                f"Part of a dense mutual-follow cluster of {len(cluster)} "
                f"accounts (likely bot network)"
            )
            _log_detection(user, BotEvent.EventType.BOT_NETWORK, reason)
            return constants.POINTS['bot_network'], reason

        return 0, None

    @staticmethod
    def check_spam_comments(user):
        comments = Comment.objects.filter(author=user).values_list(
            'content', flat=True
        )

        spam_count = 0
        for content in comments:
            if SpamClassifierService.is_spam(
                    content, constants.SPAM_CLASSIFIER_THRESHOLD
            ):
                spam_count += 1

        if spam_count >= constants.SPAM_COMMENT_COUNT_THRESHOLD:
            reason = (
                f"Classifier flagged {spam_count} comments as spam "
                f"(learned spam patterns)"
            )
            _log_detection(user, BotEvent.EventType.ML_SPAM_COMMENT, reason)
            return constants.POINTS['spam_comments_ml'], reason

        return 0, None

    @staticmethod
    def check_spam_bio(user):
        try:
            bio = user.profile.bio
        except Exception:
            return 0, None

        if not bio or not bio.strip():
            return 0, None

        probability = SpamClassifierService.spam_probability(bio)

        if probability >= constants.SPAM_CLASSIFIER_THRESHOLD:
            reason = (
                f"Classifier flagged bio as spam "
                f"({probability:.0%} confidence)"
            )
            _log_detection(user, BotEvent.EventType.ML_SPAM_BIO, reason)
            return constants.POINTS['spam_bio_ml'], reason

        return 0, None

    CHECKS = [
        check_username_pattern,
        check_username_blocklist,
        check_shared_ip,
        check_throttle_events,
        check_failed_logins,
        check_repeated_comments,
        check_spam_phrases,
        check_follow_velocity,
        check_profile_completeness,
        check_activity_burst,
        check_regular_rhythm,
        check_username_cluster,
        check_fuzzy_username_cluster,
        check_near_duplicate_comments,
        check_duplicate_posts,
        check_duplicate_image,
        check_duplicate_post_burst,
        check_bot_network,
        check_spam_comments,
        check_spam_bio,
    ]

    @staticmethod
    def recompute_user(user):
        total = 0
        reasons = []

        for check in BotDetectionEngine.CHECKS:
            points, reason = check.__func__(user)
            if points > 0:
                total += points
                reasons.append({"reason": reason, "points": points})

        user.bot_risk_score = total
        user.flag_reasons = reasons

        # Assign tier based on bands.
        if total >= constants.RISK_TIER_LIKELY_BOT:
            user.risk_level = 'likely_bot'
            user.is_flagged = True
        elif total >= constants.RISK_TIER_SUSPICIOUS:
            user.risk_level = 'suspicious'
            user.is_flagged = False
        else:
            user.risk_level = 'clean'
            user.is_flagged = False

        user.save(update_fields=[
            'bot_risk_score', 'is_flagged', 'flag_reasons', 'risk_level'
        ])

        return {
            "username": user.username,
            "score": total,
            "risk_level": user.risk_level,
            "is_flagged": user.is_flagged,
            "reasons": reasons,
        }

    @staticmethod
    def recompute_all():
        results = []
        users = User.objects.filter(is_staff=False).select_related('profile')

        for user in users:
            results.append(BotDetectionEngine.recompute_user(user))

        flagged = [r for r in results if r["is_flagged"]]
        return {
            "total_scanned": len(results),
            "total_flagged": len(flagged),
            "results": results,
        }

