# Generated by Django 6.0.3 on 2026-06-12 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('THROTTLED', 'Rate limit exceeded'), ('FAILED_LOGIN', 'Failed login attempt'), ('RAPID_FOLLOW', 'Rapid following'), ('REPEATED_COMMENT', 'Repeated identical comment'), ('SPAM_CONTENT', 'Spam phrases detected')], max_length=30)),
                ('detail', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bot_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type'], name='bot_detecti_event_t_e21e91_idx'), models.Index(fields=['created_at'], name='bot_detecti_created_5f0162_idx'), models.Index(fields=['ip_address'], name='bot_detecti_ip_addr_9bdc13_idx')],
            },
        ),
    ]
