# Generated by Django 6.0.3 on 2026-06-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_detection', '0002_blocklistterm_spamphrase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botevent',
            name='event_type',
            field=models.CharField(choices=[('THROTTLED', 'Rate limit exceeded'), ('FAILED_LOGIN', 'Failed login attempt'), ('RAPID_FOLLOW', 'Rapid following'), ('REPEATED_COMMENT', 'Repeated identical comment'), ('SPAM_CONTENT', 'Spam phrases detected'), ('SIGNUP', 'Account created'), ('LOGIN', 'Successful login')], max_length=30),
        ),
    ]
