# Generated by Django 6.0.3 on 2026-06-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_detection', '0005_alter_botevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botevent',
            name='event_type',
            field=models.CharField(choices=[('THROTTLED', 'Rate limit exceeded'), ('FAILED_LOGIN', 'Failed login attempt'), ('RAPID_FOLLOW', 'Rapid following'), ('REPEATED_COMMENT', 'Repeated identical comment'), ('SPAM_CONTENT', 'Spam phrases detected'), ('SIGNUP', 'Account created'), ('LOGIN', 'Successful login'), ('SUSPICIOUS_USERNAME', 'Suspicious username'), ('USERNAME_CLUSTER', 'Username cluster (bot farm)'), ('INCOMPLETE_PROFILE', 'Incomplete profile'), ('ACTIVITY_BURST', 'Activity burst'), ('REGULAR_RHYTHM', 'Mechanical timing rhythm'), ('DUPLICATE_POSTS', 'Near-duplicate posts'), ('DUPLICATE_IMAGE', 'Reused image across posts'), ('DUPLICATE_POST_BURST', 'Burst of duplicate posts'), ('BOT_NETWORK', 'Dense follow cluster (bot network)')], max_length=30),
        ),
    ]
