# Generated by Django 6.0.3 on 2026-06-08 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_fix_image_paths'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
