# Generated by Django 6.0.3 on 2026-06-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_profile_pic_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bot_risk_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
