# Generated by Django 6.0.3 on 2026-06-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_bot_risk_score_user_is_flagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='flag_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
