# Generated by Django 6.0.3 on 2026-06-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_flag_reasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='risk_level',
            field=models.CharField(choices=[('clean', 'Clean'), ('suspicious', 'Suspicious'), ('likely_bot', 'Likely Bot')], default='clean', max_length=20),
        ),
    ]
